//! Dispatch for builtin skill tool handlers.
//!
//! Builtin handlers are Rust functions invoked directly by the agent loop,
//! without spawning a subprocess or making an HTTP call. They have access
//! to `ToolContext` (for home_dir, etc.) and return `ToolOutput`.

use std::fmt::Write;
use std::sync::LazyLock;

use crate::tools::{ToolContext, ToolOutput};

/// Embedded OpenAPI spec for the agent (mika-server) HTTP API.
static AGENT_API_SPEC: &str = include_str!("../../../../docs/openapi/mika-server.yaml");

/// Embedded architecture overview document.
static ARCHITECTURE_OVERVIEW: &str = include_str!("../../../../docs/architecture.md");

/// Known builtin function names, used for startup validation.
pub const KNOWN_BUILTINS: &[&str] = &[
    "get_cli_reference",
    "get_api_spec",
    "get_architecture_overview",
    "web_search",
];

/// Maximum output size from a builtin handler (matches executor::MAX_OUTPUT_LEN).
const MAX_OUTPUT_LEN: usize = 10_000;

/// Maximum response body size from Brave Search API (1MB).
const MAX_SEARCH_RESPONSE_BYTES: usize = 1_024 * 1_024;

/// Shared HTTP client for builtin handlers (connection pooling, TLS reuse).
static HTTP_CLIENT: LazyLock<reqwest::Client> = LazyLock::new(|| {
    reqwest::Client::builder()
        .timeout(std::time::Duration::from_secs(15))
        .build()
        .expect("failed to build HTTP client")
});

/// Dispatch a builtin handler by function name.
///
/// Returns `ToolOutput` directly — no subprocess, no HTTP call.
/// Output is truncated to `MAX_OUTPUT_LEN` for consistency with exec/http handlers.
pub async fn execute(
    function: &str,
    input: serde_json::Value,
    ctx: &ToolContext<'_>,
) -> ToolOutput {
    let mut output = match function {
        "get_cli_reference" => get_cli_reference(ctx).await,
        "get_api_spec" => get_api_spec(&input),
        "get_architecture_overview" => get_architecture_overview(),
        "web_search" => web_search(&input, ctx).await,
        _ => ToolOutput::error(format!("Unknown builtin function: {function}")),
    };
    truncate_output(&mut output);
    output
}

/// Truncate output content to MAX_OUTPUT_LEN characters.
fn truncate_output(output: &mut ToolOutput) {
    if output.content.len() > MAX_OUTPUT_LEN {
        output.content.truncate(MAX_OUTPUT_LEN);
        output.content.push_str("\n... (truncated at 10000 chars)");
    }
}

/// Read the CLI reference markdown from the agent's home directory.
///
/// The file is generated by the CLI binary on startup and placed at
/// `{home_dir}/cli-reference.md`.
async fn get_cli_reference(ctx: &ToolContext<'_>) -> ToolOutput {
    let path = ctx.home_dir.join("cli-reference.md");
    match tokio::fs::read_to_string(&path).await {
        Ok(content) => ToolOutput::success(content),
        Err(e) => {
            tracing::warn!(error = %e, path = %path.display(), "failed to read CLI reference");
            ToolOutput::error(
                "CLI reference not found. Run the `mika` CLI once to generate it.".to_string(),
            )
        }
    }
}

/// Return the embedded OpenAPI YAML spec for the agent service.
///
/// Input: `{"service": "agent"}`
fn get_api_spec(input: &serde_json::Value) -> ToolOutput {
    let service = input.get("service").and_then(|v| v.as_str()).unwrap_or("");
    match service {
        "agent" => ToolOutput::success(AGENT_API_SPEC.to_string()),
        _ => {
            ToolOutput::error("Invalid service. Use \"agent\" for the mika-server API.".to_string())
        }
    }
}

/// Return the embedded architecture overview.
fn get_architecture_overview() -> ToolOutput {
    ToolOutput::success(ARCHITECTURE_OVERVIEW.to_string())
}

/// Search the web using the Brave Search API.
///
/// Input: `{"query": "search terms"}`
/// Requires `brave_api_key` in config or `MIKA_BRAVE_API_KEY` environment variable.
async fn web_search(input: &serde_json::Value, ctx: &ToolContext<'_>) -> ToolOutput {
    let query = match input.get("query").and_then(|v| v.as_str()) {
        Some(q) if !q.trim().is_empty() => q.trim(),
        _ => return ToolOutput::error("Missing or empty 'query' parameter.".to_string()),
    };

    // Enforce input length limit (shared tool validation convention)
    if query.len() > 10_000 {
        return ToolOutput::error("Query too long (max 10000 characters).".to_string());
    }

    let api_key = match ctx.brave_api_key {
        Some(key) if !key.trim().is_empty() => key.to_string(),
        _ => {
            return ToolOutput::error(
                "Brave Search API key not configured. \
                 Set brave_api_key in ~/.mika/config.toml or MIKA_BRAVE_API_KEY env var. \
                 Get a free key at https://brave.com/search/api/"
                    .to_string(),
            );
        }
    };

    let resp = match HTTP_CLIENT
        .get("https://api.search.brave.com/res/v1/web/search")
        .header("X-Subscription-Token", &api_key)
        .header("Accept", "application/json")
        .query(&[("q", query), ("count", "5")])
        .send()
        .await
    {
        Ok(r) => r,
        Err(e) if e.is_timeout() => {
            return ToolOutput::error("Search request timed out (15s).".to_string());
        }
        Err(_) => {
            return ToolOutput::error("Search request failed.".to_string());
        }
    };

    let status = resp.status();
    if !status.is_success() {
        let msg = match status.as_u16() {
            401 => "Invalid API key. Check MIKA_BRAVE_API_KEY.".to_string(),
            429 => "Search rate limit exceeded. Try again later.".to_string(),
            _ => format!("Search API returned HTTP {status}."),
        };
        return ToolOutput::error(msg);
    }

    // Limit response body size to prevent memory exhaustion
    let content_length = resp.content_length().unwrap_or(0) as usize;
    if content_length > MAX_SEARCH_RESPONSE_BYTES {
        return ToolOutput::error("Search response too large.".to_string());
    }

    let bytes = match resp.bytes().await {
        Ok(b) if b.len() > MAX_SEARCH_RESPONSE_BYTES => {
            return ToolOutput::error("Search response too large.".to_string());
        }
        Ok(b) => b,
        Err(_) => return ToolOutput::error("Failed to read search response.".to_string()),
    };

    let body: serde_json::Value = match serde_json::from_slice(&bytes) {
        Ok(v) => v,
        Err(_) => return ToolOutput::error("Failed to parse search response.".to_string()),
    };

    format_brave_results(&body, query)
}

/// Format Brave Search API results into concise, LLM-friendly text.
fn format_brave_results(body: &serde_json::Value, query: &str) -> ToolOutput {
    let results = body
        .get("web")
        .and_then(|w| w.get("results"))
        .and_then(|r| r.as_array());

    let results = match results {
        Some(arr) if !arr.is_empty() => arr,
        _ => {
            return ToolOutput::success(format!("No results found for \"{query}\"."));
        }
    };

    let mut out = format!("Search results for \"{query}\":\n");

    for (i, result) in results.iter().enumerate().take(5) {
        let title = result.get("title").and_then(|v| v.as_str()).unwrap_or("");
        let url = result.get("url").and_then(|v| v.as_str()).unwrap_or("");
        let description = result
            .get("description")
            .and_then(|v| v.as_str())
            .unwrap_or("");

        let _ = writeln!(out);
        let _ = writeln!(out, "{}. {}", i + 1, title);
        let _ = writeln!(out, "   URL: {url}");
        if !description.is_empty() {
            let _ = writeln!(out, "   {description}");
        }
    }

    ToolOutput::success(out)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::test_utils::test_helpers::TestHarness;

    #[test]
    fn test_get_api_spec_agent() {
        let input = serde_json::json!({"service": "agent"});
        let output = get_api_spec(&input);
        assert!(!output.is_error);
        assert!(output.content.contains("openapi"));
    }

    #[test]
    fn test_get_api_spec_gateway_returns_error() {
        let input = serde_json::json!({"service": "gateway"});
        let output = get_api_spec(&input);
        assert!(output.is_error);
    }

    #[test]
    fn test_get_api_spec_invalid() {
        let input = serde_json::json!({"service": "unknown"});
        let output = get_api_spec(&input);
        assert!(output.is_error);
    }

    #[test]
    fn test_get_architecture_overview() {
        let output = get_architecture_overview();
        assert!(!output.is_error);
        assert!(!output.content.is_empty());
    }

    #[tokio::test]
    async fn test_execute_unknown_function_returns_error() {
        let harness = TestHarness::new();
        let ctx = harness.ctx();
        let output = execute("nonexistent_function", serde_json::json!({}), &ctx).await;
        assert!(output.is_error);
        assert!(output.content.contains("Unknown builtin function"));
        assert!(output.content.contains("nonexistent_function"));
    }

    #[test]
    fn test_truncate_output_short() {
        let mut output = ToolOutput::success("short content");
        truncate_output(&mut output);
        assert_eq!(output.content, "short content");
    }

    #[test]
    fn test_truncate_output_long() {
        let long = "x".repeat(MAX_OUTPUT_LEN + 500);
        let mut output = ToolOutput::success(long);
        truncate_output(&mut output);
        assert!(output.content.contains("truncated"));
        assert!(output.content.len() < MAX_OUTPUT_LEN + 100);
    }

    #[tokio::test]
    async fn test_web_search_missing_query() {
        let harness = TestHarness::new();
        let ctx = harness.ctx();
        let output = web_search(&serde_json::json!({}), &ctx).await;
        assert!(output.is_error);
        assert!(output.content.contains("Missing or empty"));
    }

    #[tokio::test]
    async fn test_web_search_empty_query() {
        let harness = TestHarness::new();
        let ctx = harness.ctx();
        let output = web_search(&serde_json::json!({"query": "  "}), &ctx).await;
        assert!(output.is_error);
        assert!(output.content.contains("Missing or empty"));
    }

    #[tokio::test]
    async fn test_web_search_query_too_long() {
        let harness = TestHarness::new();
        let ctx = harness.ctx();
        let long_query = "x".repeat(10_001);
        let output = web_search(&serde_json::json!({"query": long_query}), &ctx).await;
        assert!(output.is_error);
        assert!(output.content.contains("too long"));
    }

    #[test]
    fn test_format_brave_results_empty() {
        let body = serde_json::json!({"web": {"results": []}});
        let output = format_brave_results(&body, "test");
        assert!(!output.is_error);
        assert!(output.content.contains("No results found"));
    }

    #[test]
    fn test_format_brave_results_with_data() {
        let body = serde_json::json!({
            "web": {
                "results": [
                    {
                        "title": "Test Result",
                        "url": "https://example.com",
                        "description": "A test description"
                    }
                ]
            }
        });
        let output = format_brave_results(&body, "test query");
        assert!(!output.is_error);
        assert!(output.content.contains("Test Result"));
        assert!(output.content.contains("https://example.com"));
        assert!(output.content.contains("A test description"));
        assert!(output.content.contains("test query"));
    }

    #[test]
    fn test_format_brave_results_no_web_key() {
        let body = serde_json::json!({"query": {}});
        let output = format_brave_results(&body, "test");
        assert!(!output.is_error);
        assert!(output.content.contains("No results found"));
    }

    #[tokio::test]
    async fn test_web_search_no_api_key() {
        let harness = TestHarness::new();
        let ctx = harness.ctx();
        // Default test context has brave_api_key: None
        let output = web_search(&serde_json::json!({"query": "test"}), &ctx).await;
        assert!(output.is_error);
        assert!(output.content.contains("not configured"));
        assert!(output.content.contains("config.toml"));
    }

    #[test]
    fn test_web_search_in_known_builtins() {
        assert!(KNOWN_BUILTINS.contains(&"web_search"));
    }
}
