name: Release-plz

on:
  push:
    branches:
      - main

jobs:
  release-plz-pr:
    name: Release PR
    runs-on: ubuntu-22.04
    if: github.repository_owner == 'senara-solutions'
    permissions:
      contents: write
      pull-requests: write
    concurrency:
      group: release-plz-pr
      cancel-in-progress: false
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.RELEASE_PLZ_TOKEN }}
      - uses: dtolnay/rust-toolchain@stable
      - uses: release-plz/action@v0.5
        with:
          command: release-pr
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_PLZ_TOKEN }}

  release-plz-release:
    name: Release
    runs-on: ubuntu-22.04
    if: github.repository_owner == 'senara-solutions'
    permissions:
      contents: write
    concurrency:
      group: release-plz-release
      cancel-in-progress: false
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.RELEASE_PLZ_TOKEN }}
      - uses: dtolnay/rust-toolchain@stable
      - uses: release-plz/action@v0.5
        with:
          command: release
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_PLZ_TOKEN }}
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
